name: cascade
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - ipython=7.18.1
  - pip=20.2.4
  - qt=5.9.7
  - numpy=1.19.2
  - scipy=1.5.2
  - matplotlib=3.3.2
  - seaborn
  - astropy=4.0.2
  - jplephem=2.15
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image=0.17.2
  - scikit-learn=0.23.0
  - setuptools
  - cython
  - networkx
  - pytest
  - tqdm
  - libgcc-ng
  - libgfortran-ng
  - numba
  - aiohttp
  - psutil
  - setproctitle
  - grpcio
  - joblib
  - pyfiglet
  - termcolor
