name: cascade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - pip
  - qt
  - numpy=1.22.1
  - scipy
  - matplotlib
  - seaborn
  - astropy
  - jplephem
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image
  - scikit-learn
  - setuptools
  - cython
  - networkx
  - pytest
  - tqdm
  - numba=0.53.1
  - aiohttp
  - psutil
  - setproctitle
  - grpcio
  - pyfiglet
  - termcolor
  - statsmodels
  - configparser
  - pip:
    - 'ray[default]'
    - batman-package
    - exotethys==2.0.2
