image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate cascade
  - pip install -r requirements2.txt

tests:
  stage: test
  script:
    - python -m unittest discover -v -p *tests.py -s tests

