image: continuumio/miniconda3:latest

stages:
  - test
  - doc

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda update conda
  - conda update --all
  - conda env create -n cascade pip -f environment.yml --force
  - source activate cascade
  - conda deactivate

unittests:
  stage: test
  script:
    - source activate cascade
    - python -m unittest discover -v -p *tests.py -s tests

pages:
  stage: doc
  script:
  - source activate cascade
  - cd docs
  - make html
  - mv build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
