image: continuumio/anaconda3:latest

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda env create -f environment.yml
  - source activate cascade
  - pip install -r requirements2.txt

tests:
  stage: test
  script:
    - python -m unittest discover -v -p *tests.py -s tests

