image: continuumio/miniconda3:latest

stages:
  - test
  - doc

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda update -n base -c defaults conda
  - conda install -n base conda-libmamba-solver
  - conda config --set experimental_solver libmamba
  - conda config --describe channel_priority
  - conda config --set channel_priority flexible
  - conda env create -f .environment-gitlab.yml
  - conda init bash
  - source ~/.bashrc
  - conda activate cascade
  - conda list

units_and_doc_tests:
  stage: test
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - python cascade/initialize/initialize.py
    - python -m unittest discover -v -p *tests.py -s tests
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

pages:
  stage: doc
  script:
  - cd docs
  - mv build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
