image: continuumio/miniconda3:latest

stages:
  - test
  - doc

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential

units_and_doc_tests:
  stage: test
  script:
    - conda update -n base -c defaults conda
    - conda env create -f .environment_gitlab.yml
    - source activate cascade
    - conda deactivate
    - source activate cascade
    - conda env update -f environment.yml
    - python -m unittest discover -v -p *tests.py -s tests
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

pages:
  stage: doc
  script:
  - cd docs
  - mv build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
