image: continuumio/miniconda3:latest

stages:
  - test
  - doc

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - export PIP_CACHE_DIR="pip-cache"
  - conda update conda
  - conda update --all

cache:
  paths:
    - pip-cache

units_and_doc_tests:
  stage: test
  script:
    - conda env create --quiet --force --file .environment_gitlab.yml
    - source activate cascade
    - pip install batman-package
    - python -m unittest discover -v -p *tests.py -s tests
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

pages:
  stage: doc
  script:
  - cd docs
  - mv build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master
