name: cascade
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.11
  - ipython=7.26.0
  - pip=21.2.2
  - qt=5.9.7
  - numpy=1.20.3
  - scipy=1.6.2
  - matplotlib=3.3.4
  - seaborn
  - astropy=4.3.1
  - jplephem=2.15
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - setuptools
  - cython
  - networkx
  - pytest=6.2.3
  - tqdm
  - numba
  - aiohttp
  - psutil
  - setproctitle
  - grpcio
  - pyfiglet
  - termcolor
  - statsmodels
  - pip:
    - ray==1.5.2
    - batman-package==2.4.6
    - git+https://github.com/ucl-exoplanets/ExoTETHyS.git@master
