name: cascade
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10, <3.12
  - ipython
  - pip
  - qt
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - astropy
  - jplephem
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image>=0.19
  - scikit-learn
  - setuptools
  - cython
  - networkx
  - pytest
  - tqdm
  - ipywidgets
  - jupyter
  - ipython
  - numba
  - aiohttp
  - psutil
  - setproctitle
  - pyfiglet
  - termcolor
  - statsmodels
  - configparser
  - h5py
  - pip:
    - 'ray[default]'
    - batman-package
    - exotethys
    - jwst
