name: cascade
channels:
  - defaults
  - conda-forge
  - http://ssb.stsci.edu/astroconda
dependencies:
  - python=3.7.3
  - ipython=7.5.0
  - pip=19.1.1
  - qt=5.9.7
  - numpy=1.16.4
  - scipy=1.2.1
  - matplotlib=3.1.0
  - seaborn
  - astropy=3.1.2
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image=0.15.0
  - scikit-learn=0.21.1
  - setuptools
  - cython
  - networkx
  - pytest
  - tqdm
  - libgcc-ng
  - libgfortran-ng
  - pip:
    - batman-package==2.4.6
