name: cascade
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8, <3.10
  - ipython
  - pip
  - qt
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - astropy
  - jplephem
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image
  - scikit-learn
  - setuptools
  - cython
  - networkx
  - pytest
  - tqdm
  - numba
  - aiohttp
  - psutil
  - setproctitle
  - grpcio
  - pyfiglet
  - termcolor
  - statsmodels
  - configparser
  - pip:
    - 'ray[default]'
    - batman-package
    - git+https://github.com/ucl-exoplanets/ExoTETHyS.git@master
