name: cascade
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - ipython=7.22.0
  - pip=21.0.1
  - qt=5.9.7
  - numpy=1.19.2
  - scipy=1.6.2
  - matplotlib=3.3.4
  - seaborn
  - astropy=4.2.1
  - jplephem=2.15
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image=0.17.2
  - scikit-learn=0.23.0
  - setuptools
  - cython
  - networkx
  - pytest=6.2.3
  - tqdm
  - numba
  - aiohttp
  - psutil
  - setproctitle
  - grpcio
  - joblib
  - pyfiglet
  - termcolor
  - statsmodels
  - pip:
    - ray==1.2.0
    - batman-package==2.4.6
    - git+https://github.com/ucl-exoplanets/ExoTETHyS.git@master
