name: cascade
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.2
  - ipython=7.13.0
  - pip=20.0.2
  - qt=5.9.7
  - numpy=1.18.1
  - scipy=1.4.1
  - matplotlib=3.1.3
  - seaborn
  - astropy=4.0.1
  - jplephem=2.14
  - photutils
  - astroquery
  - pandas
  - sphinx
  - alabaster
  - scikit-image=0.17.2
  - scikit-learn=0.22.1
  - setuptools
  - cython
  - networkx
  - pytest=5.4.2
  - tqdm
  - libgcc-ng
  - libgfortran-ng
  - numba
  - aiohttp
  - psutil
  - setproctitle
  - grpcio
  - joblib
  - pyfiglet
  - termcolor
  - pip:
    - ray==0.8.4
    - batman-package==2.4.6
